@startuml
title Buy user subscription
autonumber

actor User
participant Application
participant "Payment Service" as PS
participant "Subscription Service" as SP
database "DB" as DB

User -> Application : get all subscription plans
activate Application
Application -> Application : validate authentication
Application -> SP : fetch all subscription plans
activate SP
SP -> SP : validate request
SP -> DB : select all active subscription plans
DB --> SP : return subscription plans
SP --> Application : return subscription plan dtos
deactivate SP
Application --> User : return subscription plan dtos
deactivate Application

User -> Application : choose subscription plan
activate Application
Application -> SP : validate subscription plan
activate SP
SP -> DB : select plan by id
DB --> SP : return subscription plan
SP -> SP : check plan status and constraints
SP --> Application : return subscription plan dto
deactivate SP

Application -> PS : request payment form
activate PS
PS --> Application : return payment form
Application --> User : return payment form
deactivate Application

User -> PS : open payment form and input payment data
PS -> PS : validate payment data and perform transaction

PS --> Application : send payment notification
deactivate PS
activate Application

alt payment success
  Application -> DB : create payment record(status=SUCCESS)
  DB --> Application : ok
  Application -> DB : create user subscription(status=ACTIVE)
  DB --> Application : ok
  Application --> User : return success message
else payment failed
  Application -> DB : create payment record(status=FAILED)
  DB --> Application : ok
  Application --> User : return payment failed(reason)
deactivate Application
end

destroy User
@enduml
